+incdir+../SSP_VIP
../SSP_VIP/interface.sv
../SSP_VIP/transaction.sv

+incdir+../sequence
../sequence/pclk_test_sequence.sv

+incdir+../SSP_VIP
../SSP_VIP/sequencer.sv
../SSP_VIP/driver.sv
../SSP_VIP/monitor.sv
../SSP_VIP/scoreboard.sv
../SSP_VIP/agent.sv
../SSP_VIP/environment.sv
+incdir+../testcase
../testcase/base_test.sv
../testcase/pclk_test.sv
../testcase/baud_gen_test.sv
../testcase/data_size_test.sv
../testcase/freq_ratio_test.sv
../testcase/loopback_test.sv
../testcase/lowPwr_irDA_test.sv
../testcase/parity_error_test.sv
../testcase/pulseW_irDA_test.sv
../testcase/reset_test.sv
../testcase/sir_en_test.sv
../testcase/uart_clk_test.sv
../testcase/uart_glitch_test.sv
../testcase/uart_stop_clk_test.sv
+incdir+../tb
../tb/tb.sv
+incdir+../rtl
../rtl/apb_interface.sv